In [1]:
from sqlalchemy import create_engine
import pandas as pd
engine = create_engine('postgresql://postgres:040105@localhost:5432/NYC_Green_Taxi')

In [1]:
import pandas as pd
import os

MART_PARQUET_PATH = '../data/dataset/mart_trips_filtered.parquet'
STAGING_PARQUET_PATH = '../data/dataset/staging_trips.parquet'


if os.path.exists(MART_PARQUET_PATH):
    df_mart = pd.read_parquet(MART_PARQUET_PATH)
    print(f"Đã đọc df_mart từ Parquet (đã lọc outlier): {len(df_mart):,} dòng")
else:
    # Trường hợp dự phòng: chưa có file mart, phải làm lại từ staging
    df = pd.read_parquet(STAGING_PARQUET_PATH)
    df_mart = df[(df['trip_distance'] <= 50) & (df['trip_duration_minutes'] <= 180)]
    df_mart.to_parquet(MART_PARQUET_PATH, index=False)
    print(f"Không thấy file mart, đã lọc lại từ staging: {len(df_mart):,} dòng")

Đã đọc df_mart từ Parquet (đã lọc outlier): 6,089,082 dòng

In [ ]:
## Quan sát outlier bằng thống kê mô tả
pd.set_option('display.float_format', '{:.2f}'.format)
df[['trip_distance', 'fare_amount', 'total_amount', 'trip_duration_minutes']].describe()

'''
    Kết quả cho thấy có dấu hiệu outlier 
1. trip distance : 75% chuyến đi dưới 4.4 dặm ( khoảng 7.08 km ) thì rất hợp lý cho taxi trong thành phố . nhưng ghi nhận có max là 77.843 dặm (đi vòng quanh Trái đất 3 lần ) => có thể do lỗi GPS 
2. trip_duration_minutes : có max là 8,362 phút ≈ 139 giờ (gần 6 ngày) cho 1 chuyến taxi =>  vô lý.
3. nhìn chung cả 4 cột đều đang có thể có outlier ( vì max có giá trị lớn bất thường )
'''

       trip_distance  fare_amount  total_amount  trip_duration_minutes
count     6127325.00   6127325.00    6127325.00             6127325.00
mean            3.66        15.39         18.31                  22.32
std            31.73        13.58         14.95                  89.82
min             0.01         0.00          0.00                   0.02
25%             1.15         7.00          8.80                   7.15
50%             2.13        10.50         13.30                  12.25
75%             4.40        19.00         22.80                  21.15
max         77843.76      4011.50       4012.30                8362.60

In [ ]:
def tim_nguong_outlier(cot, df):
    Q1 = df[cot].quantile(0.25)   # giá trị mà 25% dữ liệu nhỏ hơn nó
    Q3 = df[cot].quantile(0.75)   # giá trị mà 75% dữ liệu nhỏ hơn nó
    IQR = Q3 - Q1                  # khoảng chứa "50% dữ liệu ở giữa"
    nguong_duoi = Q1 - 1.5 * IQR   # dưới ngưỡng này = bất thường thấp
    nguong_tren = Q3 + 1.5 * IQR   # trên ngưỡng này = bất thường cao
    return nguong_duoi, nguong_tren
##
cac_cot_can_check = ['trip_distance', 'fare_amount', 'total_amount', 'trip_duration_minutes']

for cot in cac_cot_can_check:
    duoi, tren = tim_nguong_outlier(cot, df)
    print(f"{cot}: ngưỡng dưới = {duoi:.2f}, ngưỡng trên = {tren:.2f}")

print('\n')

for cot in cac_cot_can_check:
    duoi, tren = tim_nguong_outlier(cot, df)
    so_outlier = df[(df[cot] < duoi) | (df[cot] > tren)]
    ty_le = len(so_outlier) / len(df) * 100
    print(f"{cot}: {len(so_outlier):,} dòng outlier ({ty_le:.2f}%)")


print('\n')
dieu_kien_outlier = pd.Series(False, index=df.index)

for cot in cac_cot_can_check:
    duoi, tren = tim_nguong_outlier(cot, df)
    dieu_kien_outlier = dieu_kien_outlier | (df[cot] < duoi) | (df[cot] > tren)

so_dong_outlier_tong = dieu_kien_outlier.sum()
print(f"Tổng số dòng outlier (ít nhất 1 cột): {so_dong_outlier_tong:,} ({so_dong_outlier_tong/len(df)*100:.2f}%)")

print('\n')
that_su_vo_ly = df[(df['trip_distance'] > 50) | (df['trip_duration_minutes'] > 180)]
print(f"Số dòng thật sự vô lý (vượt giới hạn thực tế): {len(that_su_vo_ly):,} ({len(that_su_vo_ly)/len(df)*100:.2f}%)")


df[dieu_kien_outlier][['trip_id', 'trip_distance', 'fare_amount', 'total_amount', 'trip_duration_minutes']].sample(10)

In [ ]:
df_mart = df[(df['trip_distance'] <= 50) & (df['trip_duration_minutes'] <= 180)]

In [15]:
print(f"Trước lọc: {len(df):,} dòng")
print(f"Sau lọc: {len(df_mart):,} dòng")
print(f"Đã loại bỏ: {len(df) - len(df_mart):,} dòng ({(len(df) - len(df_mart))/len(df)*100:.2f}%)")

Trước lọc: 6,127,325 dòng
Sau lọc: 6,097,794 dòng
Đã loại bỏ: 29,531 dòng (0.48%)

In [16]:
df_mart.to_parquet('data/mart_trips_filtered.parquet', index=False)
print('success')

success

In [ ]:
## tạo cột TỐC ĐỘ TRUNG BÌNH 
df_mart['avg_speed_mph'] = df_mart['trip_distance'] / (df_mart['trip_duration_minutes'] /60)
pd.set_option('display.float_format', '{:.2f}'.format)
df_mart['avg_speed_mph'].describe()

## tới đây xuất hiện max = 82380.00 => tốc độ nhanh hơn td âm thanh (cần kiểm tra outlier)

count   6097794.00
mean         14.05
std         114.53
min           0.00
25%           8.66
50%          10.97
75%          14.46
max       82380.00
Name: avg_speed_mph, dtype: float64

In [ ]:
df_mart[['trip_id', 'trip_distance', 'trip_duration_minutes', 'avg_speed_mph']].sort_values('avg_speed_mph', ascending=False).head(10)

## tới đây thì rõ ràng : có những chuyến đi có 0.02s mà đi đến tận 27km => outlier

         trip_id  trip_distance  trip_duration_minutes  avg_speed_mph
4234458  3197788          27.46                   0.02       82380.00
4022043  2981255          17.10                   0.02       51300.00
590765    615404          23.80                   0.03       47600.00
5394992  4399360          15.09                   0.02       45270.00
3907290  2863583          14.23                   0.02       42690.00
5282539  4282009          20.04                   0.03       40080.00
4727717  3706116          19.53                   0.03       39060.00
1376598  5523470          13.00                   0.02       39000.00
35364      45716          12.90                   0.02       38700.00
6016032  5043205          12.90                   0.02       38700.00

In [7]:
df_mart = df_mart[df_mart['avg_speed_mph'] <= 100]
print(f"Sau khi lọc tốc độ ảo: {len(df_mart):,} dòng")

df_mart['avg_speed_mph'].describe()

Sau khi lọc tốc độ ảo: 6,089,082 dòng

count   6089082.00
mean         12.38
std           5.87
min           0.00
25%           8.66
50%          10.96
75%          14.44
max         100.00
Name: avg_speed_mph, dtype: float64

In [3]:
## CỘT 2 : ĐÁNH DẤU KHUNG GIỜ CAO ĐIỂM 

df_mart['pickup_hour'] = df_mart['pickup_datetime'].dt.hour

df_mart['is_peak_hour'] = df_mart['pickup_hour'].apply(
    lambda h : True 
        if (7 <= h <= 9) or (17<=h <=19)
        else False 
)

df_mart['is_peak_hour'].value_counts()

is_peak_hour
False    4043191
True     2045891
Name: count, dtype: int64

In [11]:
## CỘT 3 : PHÂN LOẠI QUÃNG ĐƯỜNG : DÀI NGẮN XA 
df_mart['trip_category'] = pd.cut(
    df_mart['trip_distance'] , 
    bins = [0,2,5,50] ,
    labels =['short' , 'medium' , 'long'] 
)

df_mart['trip_category'].value_counts()

trip_category
short     2911938
medium    1863993
long      1313151
Name: count, dtype: int64

In [ ]:
##COT 4 NGAY TRONG TUAN 
df_mart['pickup_dayofweek'] = df_mart['pickup_datetime'].dt.day_name()

In [13]:
df_mart.to_parquet('data/mart_trips_filtered.parquet', index=False)
print(f"Đã lưu df_mart hoàn chỉnh: {len(df_mart):,} dòng, {df_mart.shape[1]} cột")

Đã lưu df_mart hoàn chỉnh: 6,089,082 dòng, 26 cột

In [2]:
df_mart.head(10)

,trip_id,vendor_id,pickup_datetime,dropoff_datetime,store_and_fwd_flag,rate_code_id,pu_location_id,do_location_id,passenger_count,trip_distance,...,congestion_surcharge,total_amount,payment_type,trip_type,trip_duration_minutes,avg_speed_mph,pickup_hour,is_peak_hour,trip_category,pickup_dayofweek
0,9425,2,2019-01-01 14:33:06,2019-01-01 14:40:57,N,1.0,82,83,1,1.21,...,NaN,8.30,2.0,1.0,7.85,9.248408,14,False,short,Tuesday
1,9427,2,2019-01-01 14:30:22,2019-01-01 14:41:32,N,1.0,65,37,1,2.23,...,NaN,14.69,1.0,1.0,11.17,11.978514,14,False,medium,Tuesday
2,9428,2,2019-01-01 14:14:07,2019-01-01 14:29:13,N,1.0,42,263,1,4.12,...,NaN,17.60,1.0,1.0,15.10,16.370861,14,False,medium,Tuesday
3,9429,2,2019-01-01 14:53:24,2019-01-01 14:56:35,N,1.0,42,74,1,0.98,...,NaN,7.25,1.0,1.0,3.18,18.490566,14,False,short,Tuesday
4,9431,2,2019-01-01 14:24:55,2019-01-01 14:37:05,N,1.0,47,248,1,2.07,...,NaN,11.30,1.0,1.0,12.17,10.205423,14,False,medium,Tuesday
5,9432,2,2019-01-01 14:01:54,2019-01-01 14:07:52,N,1.0,244,235,1,2.72,...,NaN,9.80,2.0,1.0,5.97,27.336683,14,False,medium,Tuesday
6,9433,2,2019-01-01 14:40:09,2019-01-01 14:55:05,N,1.0,244,238,1,4.99,...,NaN,21.36,1.0,1.0,14.93,20.053583,14,False,medium,Tuesday
7,9435,2,2019-01-01 14:13:47,2019-01-01 14:36:15,N,1.0,92,121,2,4.33,...,NaN,20.30,1.0,1.0,22.47,11.562083,14,False,medium,Tuesday
8,9436,2,2019-01-01 14:12:05,2019-01-01 14:25:17,N,1.0,42,50,1,5.42,...,NaN,18.30,2.0,1.0,13.20,24.636364,14,False,long,Tuesday
9,9437,2,2019-01-01 14:42:10,2019-01-01 14:48:45,N,1.0,152,41,1,1.03,...,NaN,7.30,2.0,1.0,6.58,9.392097,14,False,short,Tuesday

In [17]:
df_mart.to_sql(
    name='trips',
    schema='mart',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=100000
)
print(f"Đã ghi {len(df_mart):,} dòng vào mart.trips")

Đã ghi 6,089,082 dòng vào mart.trips